project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Data Analysis for Linguists in R"
  author: "Stefano Coretta"
  date: "25/01/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Week 1"
      chapters:
        - ch-research-methods.qmd
        - ch-quantitative.qmd
        - ch-r-rstudio.qmd
    - references.qmd

bibliography: "https://raw.githubusercontent.com/stefanocoretta/biblio/refs/heads/main/linguistics.bib"

format:
  html:
    theme: cosmo
    css: [webex.css]
    include-after-body: [webex.js]
    embed-resources: false
  # pdf:
  #   documentclass: scrreprt

editor: visual
callout-icon: false

