project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Data Analysis for Linguists in R"
  author: "Stefano Coretta"
  date: "25/01/2024"
  page-navigation: true
  chapters:
    - index.qmd

bibliography: linguistics.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

