project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Data Analysis for Linguists in R"
  author: "Stefano Coretta"
  date: "25/01/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - res-methods.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

