project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: Quantitative Data Analysis for Linguists in R
  author: Stefano Coretta
  date: 2025/08/13
  page-navigation: true
  chapters:
  - index.qmd
  - preface.qmd
  - part: Week 1
    chapters:
    - ch-research-methods.qmd
    - ch-research-context.qmd
    - ch-quantitative.qmd
    - ch-r-rstudio.qmd
    - ch-packages.qmd
  - part: Week 2
    chapters:
    - ch-inference.qmd
    - ch-scripts.qmd
    - ch-statistical-vars.qmd
    - ch-read-data.qmd
    - ch-sum-measures.qmd
    - ch-summarise.qmd
  - part: Week 3
    chapters:
    - ch-transform.qmd
    - ch-viz-principles.qmd
    - ch-quarto.qmd
    - ch-plotting.qmd
    - ch-research-cycle.qmd
  - part: Week 4
    chapters:
    - ch-probability.qmd
    - ch-freq-bayes.qmd
    - ch-gauss-model.qmd
    - ch-fit-model.qmd
  - part: Week 5
    chapters:
    - ch-regression-intro.qmd
    - ch-regression.qmd
    - ch-regression-draws.qmd
  - part: Week 6
    chapters:
    - ch-interim-summ.qmd
  - part: Week 7
    chapters:
    - ch-regression-cat.qmd
    - ch-regression-index.qmd
    - ch-regression-more.qmd
    - ch-null-ritual.qmd
  - part: Week 8
    chapters:
      - ch-regression-bernoulli.qmd
  - part: Week 9
    chapters:
      - ch-regression-cat-cat.qmd
      - ch-regression-interaction.qmd
      - ch-regression-interaction-index.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
    - include/webex.css
    include-after-body:
    - include/webex.js
    embed-resources: false
    df-print: paged
    number-sections: true
    fig-align: center
    link-external-icon: true
    link-external-newwindow: true

callout-icon: false

execute:
  freeze: auto
