project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Quantitative Data Analysis for Linguists in R"
  author: "Stefano Coretta"
  date: "25/01/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Week 1"
      chapters:
        - ch-research-methods.qmd
        - ch-quantitative.qmd
        - ch-r-rstudio.qmd
        - ch-packages.qmd
    - part: "Week 2"
      chapters:
        - ch-scripts.qmd
        - ch-statistical-vars.qmd
        - ch-read-data.qmd
        - ch-sum-measures.qmd
        - ch-summarise.qmd
    - references.qmd

bibliography: linguistics.bib

format:
  html:
    theme: cosmo
    css: [webex.css]
    include-after-body: [webex.js]
    embed-resources: false
  # pdf:
  #   documentclass: scrreprt

editor: visual
callout-icon: false

